### ISSUE TITLE
Unable to call getData and getAsk

### ISSUE THREAD

**Issue by karnatikiran19** [fintechee/Expert-Advisor-Studio#1]
Hi Team,

The information available to me from the website and learning tutorials shared by you is insufficient to do any significant results.

I am getting the following errors after trying different ways and testing different ways by reading all the materials available through your shared link and website.

Could you please resolve it?
[M2]: While calling getData([object Object], , Time), [M3]: error occurs: [M128]: The parameter: handle is not correct.

[M2]: While calling getData([object Object], 6, Time), [M3]: error occurs: [M127]: No data for the specific handle.
[M2]: While calling getAsk([object Object], 685421, 685421, EUR/USD), [M3]: error occurs: [M152]: The quote that you select is not an object.

Thank you
With best regards
Karnati Kiran

**Comment by fintechee** [comment]
Please share with us how you call getData and getAsk.
Type the complete source codes that call getData and getAsk.

By the way, did you sign in normally or sign in the investor mode?

**Comment by karnatikiran19** [comment]
Hi,

Now one of the EA is working. But I need help.

Q1: I want to input stop loss and profit with Buy/Sell manually in any trade. I need the EA to perform high-frequency trading based on any manual parameters or standardized parameters. So within that stop loss, take profit to buy or sell, I want the EA to open close very high trades through a standardized strategic algorithm using Fintechee. Can it be done. If so, can you share some samples and reading material to execute. High-frequency trading and scalping with proper risk management are allowed to be constructed in EA.
Q2: How do I link external liquidity providers such as Instaforex to fintechee. Can you share step by step guide?

Thank you
With best regards
Karnati Kiran.?

**Comment by fintechee** [comment]
@karnatikiran19
About your new questions, please create 2 new issue posts separately.
We have solutions for you.

And, if the current issue has been resolved, please close this issue.
As an additional tip regarding getAsk and getData, let me share some tutorial videos with you.
They may be helpful.
For calling getData:
https://www.youtube.com/watch?v=8nIhbRRPPT8
For calling getAsk:
https://www.youtube.com/watch?v=vgN5Li8QOOA

We have prepared enough tutorials for beginners.
You didn't check our site carefully.

**Comment by karnatikiran19** [comment]
Hi,

As suggested, I am closing this issue and opening two new tickets. Yes, I have gone through your website. I am good at identifying opportunities in trading markets using my methods and little bit needs improvement in coding stuff. So please bear with me I might come back to you frequently. It does not mean I am not doing my home work. It only means my strengths are at identifying trading opportunities through offline and needs improvement in coding.
